#!/bin/bash
# script to upload the currently built stm binaries to the board
# allocates gpios corresponding to the RST and BOOT0 and drives them to the proper levels
# docs for pinctrl are here: https://github.com/raspberrypi/utils/tree/master/pinctrl
# page 76 in this datasheet: https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf 
#install stm32flash via apt

#boot0, rst gpio defs in cougrc
if [[ -v UCONTROLLER_SERIAL ]]; then
    #set boot0 high, reset, upload, set boot0 low, reset again
    sudo pinctrl set $STM_BOOT0_GPIO op dh
    sudo pinctrl set $STM_RST_GPIO op dl
    sudo pinctrl set $STM_RST_GPIO op dh
    #TODO: ensure UART configuration
    #append stm32prog 
    #UART 0 as of board version B, TODO: check if this connection works fs
    STM32FLASH_CLI=stm32flash
    case $1 in
        "")
            FILEPATH=~/mcu_ws/stm/.pio/build/disco_f030r8/firmware.bin #bin file generated by platformio
            ;;
        *)
            FILEPATH=$1
            ;;
    esac

    #defaults for most options, quiet: no progress bar
    stm32flash -r "${FILEPATH}" -R "${UCONTROLLER_SERIAL}"
    sudo pinctrl $STM_BOOT0_GPIO op dl
    sudo pinctrl $STM_RST_GPIO op dl
    sudo pinctrl $STM_RST_GPIO op dh

else 
    echo -e "\033[0;31mUCONTROLLER_SERIAL not set, please set it and/or source cougrc\033[0m"
fi

