#!/bin/bash
# script to upload the currently built stm binaries to the board
# allocates gpios corresponding to the RST and BOOT0 and drives them to the proper levels
# docs for pinctrl are here: https://github.com/raspberrypi/utils/tree/master/pinctrl
# page 76 in this datasheet: https://www.st.com/content/ccc/resource/technical/document/application_note/b9/9b/16/3a/12/1e/40/0c/CD00167594.pdf/files/CD00167594.pdf/jcr:content/translations/en.CD00167594.pdf 
#install stm32flash via apt

#boot0, rst gpio defs in cougrc
if [[ -n "${UCONTROLLER_SERIAL:-}" ]]; then
    echo "Using serial ${UCONTROLLER_SERIAL} with BOOT0 GPIO ${STM_BOOT0_GPIO} and RST GPIO ${STM_RST_GPIO}"
    #set boot0 high, reset, upload, set boot0 low, reset again
    sudo pinctrl set $STM_BOOT0_GPIO op dh
    sudo pinctrl set $STM_RST_GPIO op dl
    sleep 0.1
    sudo pinctrl set $STM_RST_GPIO op dh
    sleep 0.5
    #TODO: ensure UART configuration
    #append stm32prog 
    #UART 0 as of board version B, TODO: check if this connection works fs
    case $1 in
        "")
            FILEPATH=/home/frostlab/cougars-frost/mcu_ws/stm/.pio/build/stm32f030k6tx/firmware.bin #bin file generated by platformio
            ;;
        *)
            FILEPATH=$1
            ;;
    esac

    #defaults for most options, quiet: no progress bar
    sudo stm32flash -w "${FILEPATH}" "${UCONTROLLER_SERIAL}"
    sudo pinctrl set $STM_BOOT0_GPIO op dl
    sleep 0.1
    sudo pinctrl set $STM_RST_GPIO op dl
    sleep 0.1
    sudo pinctrl set $STM_RST_GPIO op dh

else 
    echo -e "\033[0;31mUCONTROLLER_SERIAL not set, please set it and/or source cougrc\033[0m"
fi